### ISSUE TITLE
INIADのロゴをページ冒頭に追加

### ISSUE THREAD

**Issue by hi-yaguchi** [hiromu-tana/iniad-fake-homepage#3]
ページの冒頭にINIADのロゴを入れてはいかがでしょうか。

**Comment by hiromu-tana** [comment]
矢口さん、こちらアサインしてみました。
よろしくお願いいたします。

**Comment by hi-yaguchi** [comment]
分担ありがとうございます。今日は眠いので明日の朝から作業進めますね。

**Comment by hi-yaguchi** [comment]
ロゴを追加して、ロゴの背景色をネイビーにしました。ロゴサイズはもう少し小さい方がバランスが良いと思うのですが、サイズ変更の方法が分からなかったので、完了とします。
もし、サイズ変更方法が分かる方がいっらしゃれば教えてください。調整します。
なお、ロゴをクリックするとINIADのホームページへアクセスできる様にしてみました。
